name: Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
            cd /home/ubuntu
            git clone https://github.com/Khaula-cloud/Dockerised-API-with-CI-CD-on-AWS-EC2.git || \
              (cd Dockerised-API-with-CI-CD-on-AWS-EC2 && git pull)
            cd Dockerised-API-with-CI-CD-on-AWS-EC2
            docker build -t todo-api .
            docker stop todo-api-container || true
            docker rm todo-api-container || true
            docker run -d \
              --name todo-api-container \
              --restart always \
              -p 3000:3000 \
              todo-api
          EOF
